version: '3'

services:
    php:
        build:
            context: docker/php
            args:
                UID: ${UID}
                GID: ${GID}
        ports:
            - 80:80
        depends_on:
            - db
            - rabbitmq
        volumes:
            - ./shared/backend:/var/www/backend
    db:
        image: postgres:10.5
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: billing
            POSTGRES_USER: billing
            POSTGRES_PASSWORD: billing
        volumes:
            - ./docker/db-dump:/docker-entrypoint-initdb.d
    rabbitmq:
        image: rabbitmq:3.7-management-alpine
        expose:
        - 5672
        ports:
        - 5672:5672
        - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: billing
            RABBITMQ_DEFAULT_PASS: billing
            RABBITMQ_DEFAULT_VHOST: "/"
